version: '3.8'

services:
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: chat-server
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - CHAT_SERVER_HOST=0.0.0.0
      - CHAT_SERVER_PORT=8080
      - CHAT_DISCOVERY_PORT=8081
      - CHAT_LOG_LEVEL=INFO
      - CHAT_LOG_JSON=true
      - CHAT_MAX_CLIENTS=100
      - CHAT_RATE_LIMIT_MSG_PER_MIN=60
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('localhost', 8080)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Example client service (for testing)
  chat-client-demo:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: chat-client-demo
    environment:
      - CHAT_CLIENT_HOST=chat-server
      - CHAT_CLIENT_PORT=8080
      - CHAT_LOG_LEVEL=INFO
    depends_on:
      chat-server:
        condition: service_healthy
    networks:
      - chat-network
    profiles:
      - demo
    stdin_open: true
    tty: true

networks:
  chat-network:
    driver: bridge

volumes:
  chat-logs:
    driver: local
  chat-config:
    driver: local